[package]
name = "ztools-core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
flate2 = "1.1.1"
sevenz-rust = "0.6.1"
tar = "0.4.44"
walkdir = "2.5.0"

[dev-dependencies]
dir-diff = "*"
